import card1 from "./assets/images/card1.jpg";
import card2 from "./assets/images/card2.jpg";
import card3 from "./assets/images/card3.jpg";
import agent1 from "./assets/images/agent1.png";
import agent2 from "./assets/images/agent2.png";
export const properties = [
  {
    image: card1,
    title: "Luxury Family Home",
    type: "Apartment",
    status: "For Rent",
    featured: true,
    price: "15000",
    address: "1421 San Pedro St, Los Angeles, CA 900015",
    beds: 4,
    baths: 6,
    sqft: 5280,
    agent: {
      name: "Ali Tufan",
      avatar: agent1,
    },
    posted: "1 year ago",
  },
  {
    image: card2,
    title: "Renovated Apartment",
    type: "Villa",
    status: "For Rent",
    featured: true,
    price: "19000",
    address: "1421 San Pedro St, Los Angeles, CA 900015",
    beds: 4,
    baths: 1,
    sqft: 5280,
    agent: {
      name: "Ali Tufan",
      avatar: agent2,
    },
    posted: "1 year ago",
  },
  {
    image: card3,
    title: "Luxury Family Home",
    type: "Bungalow",
    status: "For Rent",
    featured: true,
    price: "13000",
    address: "1421 San Pedro St, Los Angeles, CA 900015",
    beds: 4,
    baths: 2,
    sqft: 5280,
    agent: {
      name: "Ali Tufan",
      avatar: agent1,
    },
    posted: "1 year ago",
  },
  {
    image: card3,
    title: "Luxury Family Home",
    type: "Bungalow",
    status: "For Rent",
    featured: true,
    price: "13000",
    address: "1421 San Pedro St, Los Angeles, CA 900015",
    beds: 4,
    baths: 2,
    sqft: 5280,
    agent: {
      name: "Ali Tufan",
      avatar: agent1,
    },
    posted: "1 year ago",
  },
   {
    image: card3,
    title: "Luxury Family Home",
    type: "Bungalow",
    status: "For Rent",
    featured: true,
    price: "13000",
    address: "1421 San Pedro St, Los Angeles, CA 900015",
    beds: 4,
    baths: 2,
    sqft: 5280,
    agent: {
      name: "Ali Tufan",
      avatar: agent1,
    },
    posted: "1 year ago",
  },
    {
    image: card1,
    title: "Luxury Family Home",
    type: "Apartment",
    status: "For Rent",
    featured: true,
    price: "15000",
    address: "1421 San Pedro St, Los Angeles, CA 900015",
    beds: 4,
    baths: 6,
    sqft: 5280,
    agent: {
      name: "Ali Tufan",
      avatar: agent1,
    },
    posted: "1 year ago",
  },
];

